"""Emit the paper's LaTeX result tables directly from the experiment CSVs.

Numbers in the paper are generated, never transcribed. Re-run this after
``run_paper_experiments.py`` and ``run_adult.py``.
"""

from __future__ import annotations

import argparse
import csv
import math
import os


def read_summary(path: str) -> list[dict[str, str]]:
    with open(path) as fh:
        return list(csv.DictReader(fh))


def _f(row: dict[str, str], key: str) -> float:
    value = row.get(key, "")
    if value in ("", "nan"):
        return float("nan")
    return float(value)


def _fmt(x: float, spec: str = ".3f") -> str:
    return "--" if math.isnan(x) else format(x, spec)


def main_results(
    base_dir: str, out_path: str, variants: list[tuple[str, str]], sizes: list[int]
) -> None:
    with open(out_path, "w") as fh:
        fh.write("% generated by scripts/make_tables.py\n")
        fh.write("\\begin{tabular}{ll rr rr r}\n\\toprule\n")
        fh.write(
            "variant & $n$ & $P(\\text{soln})$ & CP hi & $P(\\text{viol})$ & CP hi "
            "& log loss ($n_s$)\\\\\n\\midrule\n"
        )
        for label, directory in variants:
            path = os.path.join(base_dir, directory, "summary.csv")
            if not os.path.exists(path):
                continue
            rows = {int(float(r["m"])): r for r in read_summary(path)}
            first = True
            for size in sizes:
                if size not in rows:
                    continue
                r = rows[size]
                loss = _f(r, "log_loss")
                se = _f(r, "log_loss_se")
                loss_str = "--" if math.isnan(loss) else f"{loss:.3f}$\\pm${se:.3f}"
                fh.write(
                    f"{label if first else ''} & {size} & "
                    f"{_f(r, 'p_solution'):.2f} & {_f(r, 'p_solution_hi'):.2f} & "
                    f"{_f(r, 'p_violation'):.2f} & {_f(r, 'p_violation_hi'):.2f} & "
                    f"{loss_str} ({int(float(r['n_solutions']))})\\\\\n"
                )
                first = False
            fh.write("\\midrule\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote", out_path)


def failure_modes(base_dir: str, out_path: str, directory: str = "base") -> None:
    path = os.path.join(base_dir, directory, "summary.csv")
    rows = read_summary(path)
    with open(out_path, "w") as fh:
        fh.write("% generated by scripts/make_tables.py\n")
        fh.write("\\begin{tabular}{rrrr}\n\\toprule\n")
        fh.write("$n$ & solution & cand.\\ infeasible & safety rej.\\\\\n\\midrule\n")
        for r in rows:
            fh.write(
                f"{int(float(r['m']))} & {_f(r, 'p_solution'):.2f} & "
                f"{_f(r, 'frac_candidate_infeasible'):.2f} & "
                f"{_f(r, 'frac_safety_rejected'):.2f}\\\\\n"
            )
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote", out_path)


def adult_table(base_dir: str, out_path: str) -> None:
    variants = [
        ("$\\epsilon{=}0.1$ Hoeffding", "adult/base"),
        ("$\\epsilon{=}0.1$ emp.\\ Bernstein", "adult/ebernstein"),
        ("$\\epsilon{=}0.1$ affine forms", "adult/affine"),
        ("$\\epsilon{=}0.2$ Hoeffding", "adult_eps20/base"),
        ("$\\epsilon{=}0.2$ emp.\\ Bernstein", "adult_eps20/ebernstein"),
        ("$\\epsilon{=}0.2$ affine forms", "adult_eps20/affine"),
    ]
    with open(out_path, "w") as fh:
        fh.write("% generated by scripts/make_tables.py\n")
        fh.write("\\begin{tabular}{lrrrrr}\n\\toprule\n")
        fh.write(
            "setting & $n$ & $P(\\text{soln})$ & $P(\\text{viol})$ & "
            "log loss & true $g$\\\\\n\\midrule\n"
        )
        any_written = False
        for label, directory in variants:
            path = os.path.join(base_dir, directory, "summary.csv")
            if not os.path.exists(path):
                continue
            any_written = True
            rows = read_summary(path)
            first = True
            for r in rows:
                loss = _f(r, "log_loss")
                fh.write(
                    f"{label if first else ''} & {int(float(r['m']))} & "
                    f"{_f(r, 'p_solution'):.2f} & {_f(r, 'p_violation'):.2f} & "
                    f"{_fmt(loss)} & {_fmt(_f(r, 'g_mean'), '.4f')}\\\\\n"
                )
                first = False
            fh.write("\\midrule\n")
        if not any_written:
            fh.write("\\multicolumn{6}{c}{not run}\\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote", out_path)


def other_constraints_table(base_dir: str, out_path: str) -> None:
    """Equal opportunity and equalized odds - both outside the affine fragment."""
    blocks = [
        (
            "Equal opportunity, $\\epsilon = 0.10$",
            [
                ("Hoeffding", "eo/base"),
                ("emp.\\ Bernstein", "eo/ebernstein"),
                ("$t$-test", "eo/ttest"),
            ],
        ),
        (
            "Equalized odds, $\\epsilon = 0.15$",
            [
                ("Hoeffding", "eodds/base"),
                ("emp.\\ Bernstein", "eodds/ebernstein"),
                ("$t$-test", "eodds/ttest"),
            ],
        ),
    ]
    with open(out_path, "w") as fh:
        fh.write("% generated by scripts/make_tables.py\n")
        fh.write("\\begin{tabular}{llrrrrr}\n\\toprule\n")
        fh.write(
            "constraint & bound & $n$ & $P(\\text{soln})$ & $P(\\text{viol})$ & "
            "log loss & true $g$\\\\\n\\midrule\n"
        )
        wrote = False
        for heading, variants in blocks:
            first_block = True
            for label, directory in variants:
                path = os.path.join(base_dir, directory, "summary.csv")
                if not os.path.exists(path):
                    continue
                wrote = True
                first = True
                for r in read_summary(path):
                    loss = _f(r, "log_loss")
                    fh.write(
                        f"{heading if first_block else ''} & "
                        f"{label if first else ''} & "
                        f"{int(float(r['m']))} & {_f(r, 'p_solution'):.2f} & "
                        f"{_f(r, 'p_violation'):.2f} & {_fmt(loss)} & "
                        f"{_fmt(_f(r, 'g_mean'), '.4f')}\\\\\n"
                    )
                    first = False
                    first_block = False
                fh.write("\\addlinespace\n")
            fh.write("\\midrule\n")
        if not wrote:
            fh.write("\\multicolumn{7}{c}{not run}\\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote", out_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", required=True)
    args = parser.parse_args()
    tables = os.path.join(args.base, "tables")
    os.makedirs(tables, exist_ok=True)

    main_results(
        args.base,
        os.path.join(tables, "main_results.tex"),
        [
            ("naive tree", "base"),
            ("all three tightenings", "opt"),
            ("affine forms", "affine"),
            ("BFGS", "bfgs"),
            ("force start", "force/powell"),
            ("emp.\\ Bernstein", "ebernstein"),
        ],
        [10_000, 20_000, 40_000, 320_000],
    )
    failure_modes(args.base, os.path.join(tables, "failure_modes.tex"))
    adult_table(args.base, os.path.join(tables, "adult.tex"))
    other_constraints_table(args.base, os.path.join(tables, "other_constraints.tex"))
