"""Coverage and bound-tightness studies, written straight out as LaTeX tables.

These two tables carry the paper's central claims, so they are generated from the
code rather than transcribed: an empirical-coverage table (does the interval
actually deliver 1 - delta?) and a slack table (how much does each bound-tightening
idea buy?).
"""

from __future__ import annotations

import argparse
import math
import os
import warnings

import numpy as np
import pandas as pd
import torch

warnings.filterwarnings("ignore")

from fair_seldonian.config import SeldonianConfig  # noqa: E402
from fair_seldonian.constraints.expression_tree import (  # noqa: E402
    construct_expr_tree_base,
    eval_expr_tree_base,
)
from fair_seldonian.constraints.inequalities import (  # noqa: E402
    Inequality,
    eval_func_bound,
)
from fair_seldonian.data.synthetic import get_data  # noqa: E402
from fair_seldonian.models.logistic_regression import (  # noqa: E402
    eval_ghat,
    predict,
    simple_logistic,
)

PAPER_CONSTRAINT = "TP(1) TP(0) - abs 0.2 TP(1) * -"


#: The naive interval: a two-sided width built from the one-sided tail, with the
#: sample size taken as the number of positive labels across all groups rather
#: than the size of the group the base variable is a fraction of.
def naive_half_width(n_positive_all_groups: int, delta: float) -> float:
    return math.sqrt(math.log(1 / delta) / (2 * n_positive_all_groups))


def coverage_table(path: str, trials: int = 2000, delta: float = 0.05) -> None:
    rows = []
    rng = np.random.default_rng(11)
    for n_total, n_minority, p_true in [
        (20_000, 500, 0.30),
        (20_000, 500, 0.05),
        (20_000, 2_000, 0.30),
        (4_000, 2_000, 0.30),
    ]:
        T = pd.Series(np.array(["0"] * (n_total - n_minority) + ["1"] * n_minority))
        hits = {k: 0 for k in ("naive", "hoeffding", "bernstein", "ttest")}
        widths = {k: [] for k in hits}
        for _ in range(trials):
            Y = np.zeros(n_total, dtype=int)
            Y[: n_total - n_minority] = rng.binomial(1, 0.5, n_total - n_minority)
            minority = rng.binomial(1, p_true, n_minority)
            Y[n_total - n_minority :] = minority
            pred = np.zeros(n_total)
            pred[n_total - n_minority :] = minority
            pred[: n_total - n_minority] = rng.random(n_total - n_minority)
            Ys, preds = pd.Series(Y), torch.tensor(pred)
            estimate = float(minority.sum() / n_minority)

            w = naive_half_width(int((Y == 1).sum()), delta)
            hits["naive"] += abs(estimate - p_true) <= w
            widths["naive"].append(w)

            for key, inequality in [
                ("hoeffding", Inequality.HOEFFDING_INEQUALITY),
                ("bernstein", Inequality.EMPIRICAL_BERNSTEIN),
                ("ttest", Inequality.T_TEST),
            ]:
                lo, hi = eval_func_bound(
                    "TP(1)",
                    Ys,
                    preds,
                    T,
                    delta,
                    inequality,
                    None,
                    False,
                    False,
                    two_sided=True,
                )
                hits[key] += lo <= p_true <= hi
                widths[key].append((hi - lo) / 2)
        rows.append(
            (
                n_total,
                n_minority,
                p_true,
                {k: hits[k] / trials for k in hits},
                {k: float(np.mean(widths[k])) for k in widths},
            )
        )

    with open(path, "w") as fh:
        fh.write("% generated by scripts/run_bound_studies.py\n")
        fh.write("\\begin{tabular}{rrr|cc|cc|cc|cc}\n\\hline\n")
        fh.write(
            "&&& \\multicolumn{2}{c|}{naive} & \\multicolumn{2}{c|}{Hoeffding} "
            "& \\multicolumn{2}{c|}{emp.\\ Bernstein} "
            "& \\multicolumn{2}{c}{$t$-test}\\\\\n"
        )
        fh.write(
            "$n$ & $n_{\\mathrm{min}}$ & $p$ & cov. & width & cov. & width & "
            "cov. & width & cov. & width\\\\\n\\hline\n"
        )
        for n_total, n_min, p, cov, wid in rows:
            fh.write(
                f"{n_total} & {n_min} & {p:.2f} & "
                f"\\textbf{{{cov['naive']:.3f}}} & {wid['naive']:.4f} & "
                f"{cov['hoeffding']:.3f} & {wid['hoeffding']:.4f} & "
                f"{cov['bernstein']:.3f} & {wid['bernstein']:.4f} & "
                f"{cov['ttest']:.3f} & {wid['ttest']:.4f}\\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print("wrote", path)


def tightness_table(path: str, delta: float = 0.05) -> None:
    config = SeldonianConfig(
        constraint=PAPER_CONSTRAINT, delta=delta, candidate_ratio=0.60
    )
    variants = ["base", "mod", "const", "bound", "opt", "affine"]
    rows = []
    for n in (20_000, 80_000, 320_000):
        data = get_data(n, 5, 0.5, 0.4, 0.6, random_seed=0.5)
        X = np.asarray(data.iloc[:, :-2], dtype=float)
        Y = np.asarray(data.iloc[:, -2])
        T = np.asarray(data.iloc[:, -1])
        theta, theta1 = simple_logistic(X, Y)
        truth = float(
            eval_expr_tree_base(
                construct_expr_tree_base(PAPER_CONSTRAINT),
                Y,
                predict(theta, theta1, X),
                T,
            )
        )
        slack = {}
        for v in variants:
            slack[v] = float(eval_ghat(theta, theta1, X, Y, T, v, config)) - truth
        rows.append((n, truth, slack))

    with open(path, "w") as fh:
        fh.write("% generated by scripts/run_bound_studies.py\n")
        fh.write("\\begin{tabular}{r|" + "r" * len(variants) + "}\n\\hline\n")
        labels = {
            "base": "naive tree",
            "mod": "+ split CI",
            "const": "+ constant skip",
            "bound": "+ union merge",
            "opt": "all three",
            "affine": "affine forms",
        }
        fh.write("$n$ & " + " & ".join(labels[v] for v in variants) + "\\\\\n\\hline\n")
        for n, truth, slack in rows:
            fh.write(
                f"{n} & " + " & ".join(f"{slack[v]:.4f}" for v in variants) + "\\\\\n"
            )
        fh.write("\\hline\n")
        fh.write(
            "\\multicolumn{"
            + str(len(variants) + 1)
            + "}{l}{reduction vs.\\ naive tree}\\\\\n"
        )
        for n, truth, slack in rows[-1:]:
            fh.write(
                f"{n} & "
                + " & ".join(
                    f"{100 * (1 - slack[v] / slack['base']):.1f}\\%" for v in variants
                )
                + "\\\\\n"
            )
            fh.write(
                f"{n} & "
                + " & ".join(
                    f"{(slack['base'] / slack[v]) ** 2:.2f}$\\times$" for v in variants
                )
                + "\\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print("wrote", path)


def inequality_operating_point_table(
    path: str, delta: float = 0.05, n: int = 120_000
) -> None:
    """Half-width ratio of empirical Bernstein to Hoeffding, against the rate p."""
    with open(path, "w") as fh:
        fh.write("% generated by scripts/run_bound_studies.py\n")
        fh.write("\\begin{tabular}{r|rrr}\n\\hline\n")
        fh.write("$p$ & Hoeffding & emp.\\ Bernstein & ratio\\\\\n\\hline\n")
        for p in (0.5, 0.4, 0.3, 0.2, 0.12, 0.05):
            log_term = math.log(2 / delta)
            hoeffding = math.sqrt(log_term / (2 * n))
            variance = p * (1 - p)
            bernstein = math.sqrt(2 * variance * log_term / n) + 7 * log_term / (
                3 * (n - 1)
            )
            fh.write(
                f"{p:.2f} & {hoeffding:.5f} & {bernstein:.5f} & "
                f"{bernstein / hoeffding:.3f}\\\\\n"
            )
        fh.write("\\hline\n\\end{tabular}\n")
    print("wrote", path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--trials", type=int, default=2000)
    args = parser.parse_args()
    os.makedirs(args.out, exist_ok=True)
    tightness_table(os.path.join(args.out, "tightness.tex"))
    inequality_operating_point_table(os.path.join(args.out, "operating_point.tex"))
    coverage_table(os.path.join(args.out, "coverage.tex"), trials=args.trials)


def affine_gain_table(path: str, n: int = 320_000, delta: float = 0.05) -> None:
    """Affine compilation against both baselines, on several constraints.

    The honest comparison is the ``opt`` column: constant-skip, one shared
    interval per repeated base variable, and structural sidedness are all
    present in the Seldonian Toolkit's parse tree, so that is the bound a
    practitioner would actually face.
    """
    from fair_seldonian.constraints.fairness import (
        demographic_parity,
        error_rate_parity,
    )

    data = get_data(n, 5, 0.5, 0.4, 0.6, random_seed=0.5)
    X = np.asarray(data.iloc[:, :-2], dtype=float)
    Y = np.asarray(data.iloc[:, -2])
    T = np.asarray(data.iloc[:, -1])
    theta, theta1 = simple_logistic(X, Y)
    pred = predict(theta, theta1, X)

    def slack(constraint: str, variant: str) -> float:
        cfg = SeldonianConfig(constraint=constraint, delta=delta, candidate_ratio=0.60)
        truth = float(
            eval_expr_tree_base(construct_expr_tree_base(constraint), Y, pred, T)
        )
        return float(eval_ghat(theta, theta1, X, Y, T, variant, cfg)) - truth

    rows = [
        ("demographic parity", demographic_parity(0.1, ("1", "0"))),
        ("error-rate parity", error_rate_parity(0.1, ("1", "0"))),
        ("study constraint", PAPER_CONSTRAINT),
    ]
    with open(path, "w") as fh:
        fh.write("% generated by scripts/run_bound_studies.py\n")
        fh.write("\\begin{tabular}{lrrr|rr}\n\\toprule\n")
        fh.write(
            "& \\multicolumn{3}{c|}{bound slack} & "
            "\\multicolumn{2}{c}{affine vs.\\ standard}\\\\\n"
        )
        fh.write(
            "constraint & naive & standard & affine & tighter & data\\\\\n\\midrule\n"
        )
        for name, c in rows:
            b, o, a = slack(c, "base"), slack(c, "opt"), slack(c, "affine")
            fh.write(
                f"{name} & {b:.4f} & {o:.4f} & {a:.4f} & "
                f"{100 * (1 - a / o):.1f}\\% & {(o / a) ** 2:.1f}$\\times$\\\\\n"
            )
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote", path)


def robustness_table(path: str, n: int = 320_000, delta: float = 0.05) -> None:
    """Does the affine advantage survive imbalance and many abs terms?"""
    from fair_seldonian.constraints.affine import compile_bounds
    from fair_seldonian.constraints.fairness import demographic_parity

    def slack(constraint, variant, X, Y, T, th, t1):
        cfg = SeldonianConfig(constraint=constraint, delta=delta, candidate_ratio=0.60)
        truth = float(
            eval_expr_tree_base(
                construct_expr_tree_base(constraint), Y, predict(th, t1, X), T
            )
        )
        return float(eval_ghat(th, t1, X, Y, T, variant, cfg)) - truth

    imbalance, nesting = [], []
    dp = demographic_parity(0.1, ("1", "0"))
    for ratio in (0.5, 0.2, 0.05):
        d = get_data(n, 5, ratio, 0.4, 0.6, random_seed=0.5)
        X = np.asarray(d.iloc[:, :-2], dtype=float)
        Y = np.asarray(d.iloc[:, -2])
        T = np.asarray(d.iloc[:, -1])
        th, t1 = simple_logistic(X, Y)
        o, a = slack(dp, "opt", X, Y, T, th, t1), slack(dp, "affine", X, Y, T, th, t1)
        imbalance.append((ratio, 100 * (1 - a / o)))

    d = get_data(n, 5, 0.5, 0.4, 0.6, random_seed=0.5)
    X = np.asarray(d.iloc[:, :-2], dtype=float)
    Y = np.asarray(d.iloc[:, -2])
    T = np.asarray(d.iloc[:, -1])
    th, t1 = simple_logistic(X, Y)
    gaps = [
        "TP(1) TP(0) - abs",
        "FP(1) FP(0) - abs",
        "TN(1) TN(0) - abs",
        "FN(1) FN(0) - abs",
    ]
    for k in range(1, 5):
        tokens = list(gaps[:k]) + ["+"] * (k - 1) + [f"{0.1 * k:.1f}", "-"]
        c = " ".join(tokens)
        K = len(compile_bounds(construct_expr_tree_base(c))[0])
        o, a = slack(c, "opt", X, Y, T, th, t1), slack(c, "affine", X, Y, T, th, t1)
        nesting.append((k, K, 100 * (1 - a / o)))

    with open(path, "w") as fh:
        fh.write("% generated by scripts/run_bound_studies.py\n")
        fh.write("\\begin{tabular}{lr@{\\quad}lrr}\n\\toprule\n")
        fh.write("minority & tighter & $|\\cdot|$ terms & $K$ & tighter\\\\\n")
        fh.write("\\midrule\n")
        for i in range(max(len(imbalance), len(nesting))):
            left = (
                f"{imbalance[i][0]:.0%}".replace("%", "\\%")
                + f" & {imbalance[i][1]:.1f}\\%"
                if i < len(imbalance)
                else " & "
            )
            right = (
                f"{nesting[i][0]} & {nesting[i][1]} & {nesting[i][2]:.1f}\\%"
                if i < len(nesting)
                else " & & "
            )
            fh.write(f"{left} & {right}\\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    print("wrote", path)
